title: Ryan Hein | Software Engineer | Crypto Enthusiast
description: >
  Ryan is a skilled software engineer that creates scalable applications for companies of all sizes.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: dark # Or use dark

# Profile information
name: Ryan Hein
tagline: Software Engineer
about-description: >
  Hi! I'm Ryan. I am a skilled software engineer that has taken on numerous projects over the years. I invented the first automated mining pool deployment platform, democratizing mining pools!
pic: ryan.png  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below
# Contact links
email: me@ryanhein.com # Add your Email address
phone: 303-656-6491 # Add your Phone number
website: pexaproject.com # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: stackout # Add your Github handle
twitter: '@RyanMHein' # Add your Twitter handle

# Google Analytics Tracker
analytics: UA-125810085-4

# Google Tag Manager
tagmanager: GTM-533N3P7

# Google Conversions
conversion: AW-782371799
conversion_send: Ns3WCMb70pABENeXiPUC

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
