title: Ryan Hein | Full Stack Developer | PHP Engineer | Software Developer | Laravel Enthusiast
description: > # this means to ignore newlines until "baseurl:"
  Ryan is a Full stack, php, and laravel developer. Hire me to work for your company. I can help you build something beautiful!
  Ryan is also a people-oriented, sales professional. 
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: dark # Or use dark

# Profile information
name: Ryan Hein
tagline: Full Stack Developer
about-description: > # Add Discription
  Ryan is a Full stack, php, and laravel developer. Hire me to work for your company. I can help you build something beautiful!
  Ryan is also a people-oriented, sales professional. Please view my Resume Below. I have over 14 years expierence in PHP developement,
  and over nearly 6 years expierence in leading people. 
pic: ryan.png  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below
# Contact links
email: me@ryanhein.com # Add your Email address
phone: 303-532-9265 # Add your Phone number
website: hein.estate # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: stackout # Add your Github handle
twitter: '@RyanMHein' # Add your Twitter handle

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
